<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>PrintTool.Client.UI</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PrintTool.Client\PrintTool.Client.csproj" />
    <ProjectReference Include="..\PrintTool.Ui.Shared\PrintTool.Ui.Shared.csproj" />
  </ItemGroup>

</Project>
